// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace MyNotes.UI.Web.Controllers {
    public partial class UserController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected UserController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult UpdateUser() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.UpdateUser);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult DeleteUser() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.DeleteUser);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ResetPassword() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ResetPassword);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult UserLockStatus() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.UserLockStatus);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public UserController Actions { get { return MVC.User; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "User";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "User";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Users = "Users";
            public readonly string AddUser = "AddUser";
            public readonly string UpdateUser = "UpdateUser";
            public readonly string DeleteUser = "DeleteUser";
            public readonly string ResetPassword = "ResetPassword";
            public readonly string UserLockStatus = "UserLockStatus";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string Users = "Users";
            public const string AddUser = "AddUser";
            public const string UpdateUser = "UpdateUser";
            public const string DeleteUser = "DeleteUser";
            public const string ResetPassword = "ResetPassword";
            public const string UserLockStatus = "UserLockStatus";
        }


        static readonly ActionParamsClass_UpdateUser s_params_UpdateUser = new ActionParamsClass_UpdateUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateUser UpdateUserParams { get { return s_params_UpdateUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateUser {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DeleteUser s_params_DeleteUser = new ActionParamsClass_DeleteUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteUser DeleteUserParams { get { return s_params_DeleteUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteUser {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ResetPassword s_params_ResetPassword = new ActionParamsClass_ResetPassword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ResetPassword ResetPasswordParams { get { return s_params_ResetPassword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ResetPassword {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_UserLockStatus s_params_UserLockStatus = new ActionParamsClass_UserLockStatus();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UserLockStatus UserLockStatusParams { get { return s_params_UserLockStatus; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UserLockStatus {
            public readonly string id = "id";
            public readonly string isLocked = "isLocked";
        }
        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string _addUser = "~/Views/User/_addUser.cshtml";
            public readonly string _upgradeUser = "~/Views/User/_upgradeUser.cshtml";
            public readonly string _users = "~/Views/User/_users.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_UserController: MyNotes.UI.Web.Controllers.UserController {
        public T4MVC_UserController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Users() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Users);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddUser() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddUser);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddUser(MyNotes.UI.Web.ViewModels.Admin.User.SaveUserViewModel userViewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddUser);
            callInfo.RouteValueDictionary.Add("userViewModel", userViewModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult UpdateUser(System.Guid id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.UpdateUser);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult UpdateUser(MyNotes.UI.Web.ViewModels.Admin.User.SaveUserViewModel userViewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.UpdateUser);
            callInfo.RouteValueDictionary.Add("userViewModel", userViewModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult DeleteUser(System.Guid id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.DeleteUser);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ResetPassword(System.Guid id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ResetPassword);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult UserLockStatus(System.Guid id, bool isLocked) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.UserLockStatus);
            callInfo.RouteValueDictionary.Add("id", id);
            callInfo.RouteValueDictionary.Add("isLocked", isLocked);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
